#!/bin/bash

# Build images for all platforms and architectures

set -e

pc_distro=bookworm
rpi_distro=bookworm

version=$(date +%Y%m%d%H%M%S)

parallel --progress --bar --halt now,fail=1 <<EOF
./build-local pc $pc_distro amd64 ${version}
./build-remote steve@army rpi $rpi_distro arm64 ${version}
EOF

# The following are no longer built because nobody is using them
#./build-local pc $pc_distro i386 ${version}
#./build-remote steve@army rpi $rpi_distro armhf ${version}

./build-loaders-deb ${version}
