#!/bin/bash

# Build images for all platforms and architectures

set -e

pc_distro=bookworm
rpi_distro=bookworm

parallel --progress --bar <<EOF
./build-scripts/build-rdir pc $pc_distro amd64 rdir-pc-amd64 >rdir-pc-amd64-buildlog 2>&1
./build-scripts/build-rdir pc $pc_distro i386 rdir-pc-i386 >rdir-pc-i386-buildlog 2>&1
./build-scripts/build-rdir rpi $rpi_distro armhf rdir-rpi-armhf >rdir-rpi-armhf-buildlog 2>&1
./build-scripts/build-rdir rpi $rpi_distro arm64 rdir-rpi-arm64 >rdir-rpi-arm64-buildlog 2>&1
EOF

version=$(date +%Y%m%d%H%M%S)
./build-scripts/build-deb pc amd64 rdir-pc-amd64 ${version}
./build-scripts/build-deb pc i386 rdir-pc-i386 ${version}
./build-scripts/build-deb rpi armhf rdir-rpi-armhf ${version}
./build-scripts/build-deb rpi arm64 rdir-rpi-arm64 ${version}

./build-loaders-deb ${version}
