#!/bin/bash

# Depends:
# pxelinux syslinux-common grub-efi-amd64-signed shim-signed grub-common

set -e

if [ ${UID} != 0 ]; then
  echo "This script must be run as root."
  exit 1
fi

target=till-boot
tftpboot=$target/var/lib/tftpboot

version=$(date +%Y%m%d%H%M%S)

rm -rf $target

mkdir -p $tftpboot/casper

cp /usr/lib/PXELINUX/pxelinux.0 $tftpboot/
cp /usr/lib/syslinux/modules/bios/ldlinux.c32 $tftpboot/
mkdir -p $tftpboot/pxelinux.cfg
cp /usr/lib/grub/x86_64-efi-signed/grubnetx64.efi.signed $tftpboot/grubx64.efi
cp /usr/lib/shim/shim.efi.signed $tftpboot/bootx64.efi
mkdir -p $tftpboot/grub/fonts
cp /usr/share/grub/unicode.pf2 $tftpboot/grub/fonts/

mksquashfs rdir $tftpboot/casper/till-${version}.squashfs -noappend
chmod 644 $tftpboot/casper/till-${version}.squashfs
cp till-vmlinuz till-initrd.img filesystem.manifest README.diskdefines \
    $tftpboot/

find $target -type f -print0 | xargs -0 md5sum >md5sums
size=$(du -s $target | cut -f 1)
mkdir -p $target/DEBIAN

cat >$target/DEBIAN/control <<EOF
Package: till-boot-xenial
Version: ${version}
Architecture: all
Maintainer: Stephen Early <steve@assorted.org.uk>
Installed-Size: ${size}
Depends: tftpd-hpa, nfs-kernel-server, syslinux
Conflicts: till-boot, till-boot-precise, till-boot-trusty
Priority: optional
Description: Remote boot support for simple cash register software
 Developed for Individual Pubs Limited in the UK.
EOF

mv md5sums $target/DEBIAN/

dpkg-deb -Znone -b $target .
