#!/bin/bash

echo
echo "Starting display board..."

# Ensure we start with a fresh labwc configuration directory
labwc_config=mode-displayboard-labwc-config
rm -rf ${labwc_config}
mkdir ${labwc_config}

# XXX We should make the xkb settings configurable — allow them to be
# set for the OS tty as well as the compositor!
cat >${labwc_config}/environment <<EOF
XKB_DEFAULT_LAYOUT=gb
EOF

cat >${labwc_config}/rc.xml <<EOF
<?xml version="1.0"?>
<labwc_config>
<keyboard>
<keybind key="A-Tab">
  <action name="NextWindow" />
</keybind>
<keybind key="A-S-Tab">
  <action name="PreviousWindow" />
</keybind>
<keybind key="A-F4">
  <action name="Close" />
</keybind>
<keybind key="C-A-T">
  <action name="Execute" command="lxterminal" />
</keybind>
</keyboard>
</labwc_config>
EOF

cat >display-script.sh <<EOF
#!/bin/bash

./display-browser.py $(jq -r '."display-url" // "https://quicktill.assorted.org.uk/"' config.json) >display.log

if [ -s display.log ]; then
  zenity --title="Browser output" --text-info --filename display.log \\
    --width=1600 --height=800
fi

sleep 1

# labwc should exit after this script exits

EOF
chmod +x display-script.sh

exec labwc -C ${labwc_config} -S ./display-script.sh
