#!/bin/bash

# This script invokes a web browser, full-screen
# It lives in /home/till/

matchbox-window-manager -use_titlebar no -use_cursor no &
xset s off
xset -dpms
xset s noblank
x-www-browser --start-fullscreen $(cat display-url)
sleep 1
exit
