#!/bin/bash

database=$(jq -r '{dbname: .dbname, host: .dbhost, user: .dbuser, password: .dbpassword} | to_entries | map(select(.value != null)) | map(.key+"="+.value) | join(" ")' config.json)

cat >wayfire-till.ini <<EOF
[core]
plugins = animate autostart command fast-switcher grid idle move place switcher window-rules wm-actions
plugins_nogl = animate autostart command fast-switcher grid idle move place switcher window-rules wm-actions
xwayland = false

[command]
binding_terminal = <ctrl> <alt> KEY_T
command_terminal = lxterminal
binding_quit = <ctrl> <alt> KEY_DELETE
command_quit = /usr/sbin/reboot
binding_power = KEY_POWER
command_power = /usr/sbin/poweroff

[input]
xkb_model = pc105
xkb_layout = gb
xkb_variant =

[idle]
screensaver_timeout = -1
dpms_timeout = $(jq '."screen-blank-timeout" // 300' config.json)

[autostart]
autostart_wf_shell = false
till = /home/till/runtill-script.sh
EOF

cat >runtill-script.sh <<EOF
#!/bin/bash

runtill \\
  -u $(jq -r .configurl config.json) \\
  -c $(jq -r '.configname // "default"' config.json) \\
  -d "${database}" \\
  start \\
    --gtk \\
    --fullscreen \\
    $(jq -r 'if (.keyboard // false) != false then "--keyboard" else "" end' config.json) \\
    $(jq -r 'if (.keyboard // false) == "onscreen-only" then "--no-hardware-keyboard" else "" end' config.json) \\
    --font="sans $(jq -r '.fontsize // 20' config.json)" \\
    --monospace-font="monospace $(jq -r '.fontsize // 20' config.json)" \\
    -e 0 "Restart till software" \\
    -e 20 "Power off till" \\
    -e 30 "Reboot till" \\
    -i 40 > runtill.log 2>&1

tillexit=\$?

case "\${tillexit}" in
  0) ;;
  20) sudo poweroff ;;
  30) sudo reboot ;;
  40) ;;
  *) echo "Till exit status was \${tillexit}" >>runtill.log
     zenity --title="Till errors" --text-info --filename runtill.log ;;
esac
sleep 1

# Attempt to kill wayfire
python3 wayland-logout.py

EOF
chmod +x runtill-script.sh

exec wayfire -c wayfire-till.ini
