#!/bin/bash

# This script invokes the till software and deals with any exit code.
# It lives in /home/till/

matchbox-window-manager -use_titlebar no -use_cursor $(cat pointer) &
xset s off
source runtill-command
tillexit=$?
case "$tillexit" in
  0) exit ;;
  20) sudo poweroff ;;
  30) sudo reboot ;;
  40) exit ;;
esac
sleep 1
exit
