# This file should usually be called /etc/till-boot/config.toml

# This is a "new-style" till boot configuration file which explicitly
# configures the drivers it uses and does not rely on the fallback
# code in till-boot-config

[driver.generic]
# class = "generic"

[driver.generic.defaults]
hello = "world"

[driver.till-boot]
# class = "till-boot"

# Location served by tftpd: we write to this directory
tftp-dir = "/var/lib/tftpboot"

# Location served over nfs: we read from this directory
# We expect subdirectories to be named platform/arch/version and to
# contain an image-info.yaml file
# Versions are treated as integers; higher numbers are more recent
nfs-dir = "/usr/share/till-boot"

# Bootloaders: all files here are copied to tftp-dir
loaders-dir = "/usr/share/till-boot/loaders"

# Location of kernels and initrds extracted from squashfs.  We read
# from this directory.  We expect subdirectories to be named
# platform/arch/version and to correspond to those in nfs-dir
boot-dir = "/var/lib/till-boot"

# Location served over http: we write to this directory
# Permitted to be the same as tftp-dir
http-dir = "/var/lib/tftpboot"

# Address of TFTP server serving tftp-dir
tftp-server = "192.168.73.30"  # IP address

# Address of NFS server serving nfs-dir
nfs-server= "192.168.73.30"  # IP address

# URL of http server serving http-dir
http-server = "http://192.168.73.30/till-boot/"

[driver.till-boot.defaults-pc]
architecture = "amd64"
numlock = true

[driver.till-boot.defaults-rpi]
architecture = "arm64"
numlock = false
config-pi4 = [
  # "pi4-only option for config.txt",
]
config = [
  # "general option for config.txt",
]

[role.till]
driver = "till-boot"
platform = "pc"
version = "latest"
configurl = "http://192.168.73.30/emfcamp.py"
configname = "default"
dbname = "emfcamp"
dbhost = "192.168.73.30"
dbuser = "steve"
install = [
  "quicktill22",
]
fontsize = "12"
pointer = true
repos = [
   "deb [trusted=yes] http://192.168.73.30/software tills main",
]

[defaults]
role = "till"

# The tills and their individual options are listed below.
[tills]

[tills.test-generic]
driver = "generic"
foo = "bar"

[tills.test-till-vm]
#architecture = "i386"
configname = "mainbar"
keyboard = true

[tills.test-till-vm-efi]
architecture = "amd64"
configname = "mainbar"

[tills.test-netboot-till]
configname = "mainbar"
architecture = "i386"
append = [
  "video=LVDS-1:d",
]
extra-install = [
  "till-boot-disable-lvds",
]

[tills.drone]
configname = "default"
architecture = "amd64"
fontsize = "16"
pointer = false

[tills.test-till]
configname = "stockterminal"

[tills.pi1]
platform = "rpi"
serial = "a6d7c064"
mac = "b8:27:eb:d7:c0:64"
config = [
  "start_debug=1",
  "dtoverlay=disable-bt",
  "uart_2ndstage=1",
]

[tills.pi3]
platform = "rpi"
serial = "70730e89"
mac = "b8:27:eb:73:0e:89"
keyboard = true
# Use this firmware, not the firmware from the image
#override-firmware = "/home/steve/large/firmware/boot"
config = [
  #"start_debug=1",
  "dtoverlay=disable-bt",
  "uart_2ndstage=1",
]

[tills.pi4]
platform = "rpi"
serial = "7c622f07"
keyboard = "yes"
mac = "11:22:33:44:55:66"
ipv4 = "172.31.172.45"
