%YAML 1.1
---
# This file should usually be called /etc/till-boot/config

# The configuration generator assumes that there is a DHCP server set up
# with the following in its configuration file:

# option arch code 93 = unsigned integer 16;
# [...]
# group {
#   if exists user-class and option user-class = "iPXE" {
#     filename = concat (host-decl-name, ".ipxe");
#   } elsif option arch = 00:07 {
#     filename "ipxe.efi";
#   } else {
#     filename "ipxe.pxe";
#   }
#
#   next-server [the tftp server];
#
# [and then for every network booted till...]
#   host test-till {
#     hardware ethernet 08:00:27:db:57:9a;
#     fixed-address test-till;
#   }
#
# }

# Boot configuration files will be generated for each network booted
# till and made available on the TFTP server as [till-name].ipxe - so,
# test-till.ipxe for the example above.

# Runtime configuration files will be generated for each network
# booted till and made available on the http server as
# [till-name].yaml

# Location served by tftpd: we put bootloaders, kernels, initrds and
# boot config files here
tftp-dir: /var/lib/tftpboot

# Location served over nfs: squashfs is read from here
# We expect subdirectories to be named distribution/arch/version
# Versions are treated as integers; higher numbers are more recent
nfs-dir: /usr/share/till-boot

# Bootloaders: all files here are copied to tftp-dir
loaders-dir: /usr/share/till-boot/loaders

# Location of kernels and initrds extracted from squashfs
# We expect subdirectories to be named distribution/arch/version
# and within those, kernels to be named vmlinuz and initrds initrd.img
boot-dir: /var/lib/till-boot

# Location served over http: run-time config is read from here
http-dir: /var/lib/till-boot-config

# Address of NFS server serving squashfs
nfs-server: 192.168.73.30 # IP address

# URL of http server serving run-time config
http-server: http://192.168.73.30/till-boot/

# This list of options is appended to the kernel command line for all tills
#default-append:
# - not-usually-used

defaults:
  distribution: bionic
  architecture: amd64
  version: latest
  configname: default
  dbname: haymakers
  dbhost: 192.168.73.30
  dbuser: steve
  install:
   - quicktill-nfc-bridge
   - ipl-timesheets
   - quicktill16
  fontsize: 12
  repos:
   - "deb [trusted=yes] http://192.168.73.30/software bionic-tills main"

# The tills and their individual options are listed below.
tills:
  test-till:
    configname: stockterminal

  test-till-two:
    append:
     - kernel-command-line-option-for-this-till-only
     - video=LVDS-1:d
    configname: mainbar
    architecture: i386
    extra-install:
     - python3-dali
     - till-boot-disable-lvds
    keyboard: yes
