# This file should usually be called /etc/till-boot/config.toml

# This is a "new-style" till boot configuration file which explicitly
# configures the drivers it uses and does not rely on the fallback
# code in till-boot-config

[network]
# This section controls the generation of network configuration
# files. If you do not need till-boot-config to generate these files,
# you can omit this section.

# When a till client needs to communicate with the internet, its
# traffic will be forwarded via this interface. Leave unset to
# prevent till clients from communicating with the internet.
upstream-interface = "enp1s0"

# The interface that the till clients are attached to
interface = "enp2s0"

# The IPv4 network for the till clients; the host part is the
# address the till server will have
ipv4 = "172.31.172.1/24"

# Where to write the systemd-networkd configuration file for the tills
# network
network-file = "/etc/systemd/network/10-tills.network"

# Where to write the nftables configuration file that controls
# firewalling and forwarding/masquerading from the tills network to
# the upstream network
nftables-file = "/etc/nftables.conf"

# Where to write the Kea DHCP server configuration file. It will
# contain a reservation for every till that has a "mac" configuration
# setting.
kea-dhcp4-file = "/etc/kea/kea-dhcp4.conf"

# Additional TCP ports can be opened in the firewall by adding
# [[network.firewall-accept]] sections here

# [[network.firewall-accept]]
# port = 5432  # postgresql
# network = "172.30.53.129/32"  # ur.i.individualpubs.co.uk


# An example driver that does not write any configuration files. It
# can be used to reserve IP addresses on the tills network for things
# that are not till clients.
[driver.generic]
# By default, the class used for a driver will match the driver's
# name. You only need to specify class explicitly if you are creating
# a driver with a different name from the class.

# class = "generic"

[driver.generic.defaults]
hello = "world"

# The driver that writes till configuration and boot files.
[driver.till-boot]
# class = "till-boot"

# Location served by tftpd: we write to this directory
tftp-dir = "/var/lib/tftpboot"

# Location served over nfs: we read from this directory
# We expect subdirectories to be named platform/arch/version and to
# contain an image-info.json file
nfs-dir = "/usr/share/till-boot"

# Bootloaders: all files here are copied to tftp-dir
loaders-dir = "/usr/share/till-boot/loaders"

# Location of kernels and initrds extracted from squashfs.  We read
# from this directory.  We expect subdirectories to be named
# platform/arch/version and to correspond to those in nfs-dir
boot-dir = "/var/lib/till-boot"

# Location served over http: we write to this directory
# Permitted to be the same as tftp-dir
http-dir = "/var/lib/tftpboot"

[driver.till-boot.defaults-pc]
architecture = "amd64"
numlock = true

[driver.till-boot.defaults-rpi]
architecture = "arm64"
numlock = false
config-pi4 = [
  # "pi4-only option for config.txt",
]
config = [
  # "general option for config.txt",
]

# A role is a named set of defaults
[role.till]
driver = "till-boot"
platform = "pc"
version = "latest"
configurl = "http://172.31.172.1/emfcamp.py"
configname = "default"
dbname = "emfcamp"
dbhost = "172.31.172.1"
dbuser = "till"
install = [
  "quicktill24",
]
fontsize = "12"
pointer = false
repos = [
   "deb [trusted=yes] http://172.31.172.1/software tills main",
]

[defaults]
role = "till"

# The tills and their individual options are listed below.
[tills]

[tills.test-generic]
driver = "generic"
foo = "bar"
ipv4 = "172.31.172.23"

[tills.test-till-vm]
configname = "mainbar"
keyboard = true

[tills.test-till-vm-efi]
architecture = "amd64"
configname = "mainbar"

[tills.test-netboot-till]
configname = "mainbar"
append = [
  "video=LVDS-1:d",
]
extra-install = [
  "till-boot-disable-lvds",
]

[tills.drone]
configname = "default"
architecture = "amd64"
fontsize = "16"
pointer = false
ipv4 = "172.31.172.3"

[tills.test-till]
configname = "stockterminal"

[tills.pi1]
platform = "rpi"
serial = "a6d7c064"
mac = "b8:27:eb:d7:c0:64"
config = [
  "start_debug=1",
  "dtoverlay=disable-bt",
  "uart_2ndstage=1",
]

[tills.pi3]
platform = "rpi"
serial = "70730e89"
mac = "b8:27:eb:73:0e:89"
keyboard = true
# Use this firmware, not the firmware from the image
#override-firmware = "/home/steve/large/firmware/boot"
config = [
  #"start_debug=1",
  "dtoverlay=disable-bt",
  "uart_2ndstage=1",
]

[tills.pi4]
platform = "rpi"
serial = "7c622f07"
keyboard = "yes"
mac = "11:22:33:44:55:66"
ipv4 = "172.31.172.45"
