%YAML 1.1
---
# This file should usually be called /etc/till-boot/config

# For PC booting, there must be a DHCP server set up with the
# following in its configuration file:

# option arch code 93 = unsigned integer 16;
# [...]
# group {
#   if exists user-class and option user-class = "iPXE" {
#     filename = concat (host-decl-name, ".ipxe");
#   } elsif option arch = 00:07 {
#     filename "ipxe.efi";
#   } else {
#     filename "ipxe.pxe";
#   }
#
#   next-server [the tftp server];
#
# [and then for every network booted till...]
#   host test-till {
#     hardware ethernet 08:00:27:db:57:9a;
#     fixed-address test-till;
#   }
#
# }

# Boot configuration files will be generated for each till PC and made
# available on the TFTP server as [till-name].ipxe - so,
# test-till.ipxe for the example above.  The kernel and initrd will be
# installed on the HTTP server.

# For Raspberry PI booting, there must be a DHCP server set up with
# the following in its configuration file:

# group {
#  option vendor-encapsulated-options 6:1:3:a:4:0:50:58:45:9:14:0:0:11:52:61:73:70:62:65:72:72:79:20:50:69:20:42:6f:6f:74:ff; # "Raspberry Pi Boot"
#  option vendor-class-identifier "PXEClient";
#  option tftp-server-name "[the IP address of the TFTP server]";
#
# [and then for every network booted till...]
#   host pi3 {
#     hardware ethernet b8:27:eb:73:0e:89;
#     fixed-address pi3;
#   }
#
# }

# A boot configuration directory will be generated for each till,
# named by the Raspberry PI's serial number, containing the firmware,
# kernel and initrd files from the boot image and custom generated
# config.txt and cmdline.txt files.

# Runtime configuration files will be generated for each network
# booted till and made available on the http server as
# [till-name].yaml

# Location served by tftpd: we write to this directory
tftp-dir: /var/lib/tftpboot

# Location served over nfs: we read from this directory
# We expect subdirectories to be named platform/arch/version and to
# contain an image-info.yaml file
# Versions are treated as integers; higher numbers are more recent
nfs-dir: /usr/share/till-boot

# Bootloaders: all files here are copied to tftp-dir
loaders-dir: /usr/share/till-boot/loaders

# Location of kernels and initrds extracted from squashfs.  We read
# from this directory.  We expect subdirectories to be named
# platform/arch/version and to correspond to those in nfs-dir
boot-dir: /var/lib/till-boot

# Location served over http: we write to this directory
# Permitted to be the same as tftp-dir
http-dir: /var/lib/tftpboot

# Address of TFTP server serving tftp-dir
tftp-server: 192.168.73.30 # IP address

# Address of NFS server serving nfs-dir
nfs-server: 192.168.73.30 # IP address

# URL of http server serving http-dir
http-server: http://192.168.73.30/till-boot/

defaults:
  platform: pc
  version: latest
  configurl: http://192.168.73.30/emfcamp.py
  configname: default
  dbname: emfcamp
  dbhost: 192.168.73.30
  dbuser: steve
  install:
   - quicktill19
  fontsize: 12
  pointer: yes
  repos:
   - "deb [trusted=yes] http://192.168.73.30/software tills main"

defaults-pc:
  architecture: amd64

defaults-rpi:
  architecture: arm64
  #config-pi4:
  # - pi4-only option for config.txt
  #config:
  # - general option for config.txt

# The tills and their individual options are listed below.
tills:
  test-till-vm:
    #architecture: i386
    configname: mainbar
    keyboard: yes

  test-till-vm-efi:
    architecture: amd64
    configname: mainbar

  test-netboot-till:
    configname: mainbar
    architecture: i386
    append:
     - video=LVDS-1:d
    extra-install:
     - till-boot-disable-lvds

  drone:
    configname: default
    architecture: amd64
    fontsize: 16
    pointer: no

  test-till:
    configname: stockterminal

  pi1:
    platform: rpi
    serial: a6d7c064
    mac: b8:27:eb:d7:c0:64
    config:
      - start_debug=1
      - dtoverlay=disable-bt
      - uart_2ndstage=1

  pi3:
    platform: rpi
    serial: 70730e89
    mac: b8:27:eb:73:0e:89
    keyboard: yes
    # Use this firmware, not the firmware from the image
    #override-firmware: /home/steve/large/firmware/boot
    config:
      #- start_debug=1
      - dtoverlay=disable-bt
      - uart_2ndstage=1

  pi4:
    platform: rpi
    serial: 7c622f07
    keyboard: yes
